In [ ]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
np.zeros((3, 3))
np.ones((2, 4))
np.eye(3)
np.arange(0, 10, 2)
np.linspace(0, 1, 5)
np.random.rand(3, 2)
np.random.randn(3, 2)

array([[ 1.26850438,  0.26362856],
       [-0.92788024,  1.04986497],
       [ 0.13052036,  0.62290329]])

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [11]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B

array([[19, 22],
       [43, 50]])

In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B

array([[19, 22],
       [43, 50]])

In [ ]:
arr = np.array([1, 2, 3, 4])
arr.sum()
arr.mean()
arr.max()
arr.min()
arr.std()

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr[0]

arr[1:4]
arr[::2]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]
arr[:, 1]
arr[1, :2]

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr &gt; 3
arr[mask]

In [ ]:
arr = np.arange(6)
arr.reshape(2, 3)

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

In [ ]:
np.vstack((a, b))
np.hstack((a, b))

In [ ]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]

In [ ]:
# Save to a file
np.save('array.npy', arr)

In [ ]:
# Load from a file
loaded_arr = np.load('array.npy')